version: "3.9"
services:
  app:
    labels: 
      - app.design-patterns
    hostname: app
    container_name: design-patterns
    volumes: 
      - ./:/var/www/html
    build:
      context: containers/app/
      dockerfile: Dockerfile.dev
      args:
        - TIMEZONE=America/Manaus
    image: heitor92/design-patterns:latest
    ports:
      - "80:80"
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: teste
    ports:
      - "3306:3306"
    