FROM php:7.4.19-apache

ARG USERNAME=vscode
ARG USER_UID=1000
ARG USER_GID=$USER_UID

ARG TIMEZONE

ENV TZ=${TIMEZONE}
ENV APACHE_DOCUMENT_ROOT /var/www/html/public

# Create the user
RUN groupadd --gid $USER_GID $USERNAME \
    && useradd --uid $USER_UID --gid $USER_GID -m $USERNAME \
    && usermod --shell /bin/bash $USERNAME \
    && mv "$PHP_INI_DIR/php.ini-development" "$PHP_INI_DIR/php.ini" \
    && sed -ri -e 's!/var/www/html!${APACHE_DOCUMENT_ROOT}!g' /etc/apache2/sites-available/*.conf \
    && curl -sL https://deb.nodesource.com/setup_14.x | bash - \
    && apt install -y libzip-dev zip unzip nodejs git \
    && pecl install xdebug \
    && docker-php-ext-enable xdebug \
    && docker-php-ext-configure bcmath --enable-bcmath \
    && docker-php-ext-install -j$(nproc) bcmath \
    && docker-php-ext-configure zip \
    && docker-php-ext-install -j$(nproc) zip \
    && docker-php-ext-configure pdo_mysql --with-pdo-mysql \
    && docker-php-ext-install -j$(nproc) pdo_mysql \
    && echo "xdebug.mode = debug,develop,trace" >> $PHP_INI_DIR/conf.d/docker-php-ext-xdebug.ini \
    && echo "xdebug.client_port = 9003" >> $PHP_INI_DIR/conf.d/docker-php-ext-xdebug.ini \
    && echo "xdebug.log=/tmp/xdebug.log" >> $PHP_INI_DIR/conf.d/docker-php-ext-xdebug.ini \
    && echo "xdebug.discover_client_host = true" >> $PHP_INI_DIR/conf.d/docker-php-ext-xdebug.ini \
    && a2enmod rewrite \
    && ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone 

RUN php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" \
    && php -r '$checksum = file_get_contents("https://composer.github.io/installer.sig"); \
    if (hash_file("sha384", "composer-setup.php") === $checksum) { echo "Installer verified"; } else { echo "Installer corrupt"; unlink("composer-setup.php"); } echo PHP_EOL;' \
    && php composer-setup.php --install-dir=/usr/local/bin --filename=composer \
    && php -r "unlink('composer-setup.php');"

RUN chown vscode:vscode /tmp/xdebug.log

# [Optional] Set the default user. Omit if you want to keep the default as root.
USER $USERNAME






